spring:
 application:
    name: gateway-api
 cloud:
   gateway:
       routes:
#http://localhost:9000/catalog/v1/** ---->http://localhost:8084/catalog-service/v1/**
          - id: catalogService
            uri: http://product-catalog:8084
            predicates: 
             - Path= /catalog/v1/**  
            filters:
              - AddRequestHeader=X-inventory-header,inventory-SERVICE
              - AddResponseHeader=X-inventory-responsetime,"#{T(java.time.LocalDate).now()}"
              - RewritePath=/catalog/v1/(?<segment>.*),/catalog-service/v1/${segment}

#http://localhost:9000/inventory/v1/** ---->http://localhost:8087/inventory-service/v1/**
          - id: inventoryService
            uri: http://product-inventory:8087
            predicates: 
              - Path= /inventory/v1/**
            filters:
             - RewritePath=/inventory/v1/(?<segment>.*),/inventory-service/v1/${segment}

# http://localhost:9000/info-service/v1/**
          - id: infoService
            uri: http://product-info:8082
            predicates: 
              - Path= /info-service/v1/**
# http://localhost:9000/cart-service/v1/**
          - id: cartService
            uri: http://cart-service:8089
            predicates: 
              - Path= /cart-service/v1/**

#add routing for the services
# Enable CORS for Cross-Origin Acces

management:
  endpoints:
    web:
      exposure:
        include: '*'   

server:
  port: 9000