spring:
  application:
    name: config-server
# specify the location of git hub repo
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/RamyaKDev/MicroserviceGitConfig.git
server:
  port: 8888

#access the yml file as
#http://localhost:8888/product-catalog.yml