server:
  port: 8093


spring:
 application:
  name: product-notification
 kafka:
   consumer:
     group-id: notify-id
     bootstrap-servers:
       - kafka:9092   #kafka is the service name in docker
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       "[spring.json.trusted.packages]": "*"
       "[spring.json.value.default.type]": "com.notificationservice.model.OrderEvent"

#use this for creating a bean for JavaMailSender or create a bean
mail:
  host: smtp.gmail.com
  username: ramyakpass@gmail.com
  password: godd kmij bhcj dhja 
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
         enable: true
       
