server:
  port: 8081


#
message: In catalog service
spring:
 application:
  name: product-catalog
# profiles:
#  active: dev,prod
# provide cloud config uri

 config:
  import: configserver:http://config-server:8888
# profiles:
#    active: prod,dev
#datasource specific properties
# datasource:
#    username: root
#    password: abcd
#    url: jdbc:mysql://localhost:3306/ecommdb
###jpa properties
#
# jpa:
#   hibernate:
#      ddl-auto: update
#   show-sql: true
#  



